erDiagram
  PARTICIPANT {
    string Participant_ID PK
    string Last_Name
    string First_Name
    string Address
    string City
    string State
    string Postal_Code
    string Telephone
    date Date_Of_Birth
  }
